"""
# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# TauDEM_all.py
# Created on: 2018-01-20 12:04:03.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# Follows the steps in this guide:
# http://hydrology.usu.edu/taudem/taudem5/TauDEM53GettingStartedGuide.pdf
# ---------------------------------------------------------------------------


#next:

#check with other test DEMs, check with multiple outlets

Instructions:
    - TauDEM and ArcGIS must be installed to use
    - update path to TauDEM toolbox if different
    - update path to folder path that houses DEM and outlet point shapefile(s)
    - update filename to desired name of output files.
    - do not overwrite files - it causes an error.
    - output shapefiles are not projected.

Notes: script tested on ArcGIS 10.4.1 using advanced desktop license
All test DEMS were either DEM or tif.
Tested with: cubdem, logan, ches1, SCLA base_z , la entrada

eno: error calculating area of polygons in shapefile - due to projection. hasn't occurred for anything else.
"""

# Import arcpy module
import arcpy
import os
import arcinfo         #checks out advanced license needed for last step


""" Load required TauDEM toolboxes - change path """
arcpy.ImportToolbox("C:/Program Files/TauDEM/TauDEM5Arc/TauDEM Tools.tbx")

""" set working directory and workspaces  """
path = r"C:\Program Files\TauDEM\SCLA"

""" update to desired filename """
filename = "SCLA"

""" update INPUT RASTER - put full path and name if not in same folder as path """
inDEM = "base_z.tif"

""" update INPUT OUTLET POINT SHAPEFILE. if no outlet, it should be "". Put full path and name if not in same folder as path  """
Gauge_shp = ""

arcpy.env.scratchWorkspace = path

arcpy.env.workspace = path

os.chdir(path)

#PRODUCTS - DUPLICATES ARE NUMBERED BY STEP IN TUTORIAL
fel_tif = filename +"fel.tif"
sd8_tif = filename + "sd8.tif"
p_tif = filename + "p.tif"
gord_tif = filename + "gord.tif"
plen_tif = filename + "plen.tif"
tlen_tif = filename + "tlen.tif"
slp_tif = filename + "slp.tif"
ang_tif = filename + "ang.tif"
sca_tif = filename + "sca.tif"
ad8_tif = filename + "ad8.tif"
ssa_tif = filename + "ssa.tif"
src18_tif = filename + "src2.tif"
ord19_tif = filename + "ord19.tif"
tree19_txt = filename + "tree19.txt"
coord19_txt = filename + "coord19.txt"
net19_shp = filename + "net19.shp"
w19_tif = filename + "w19.tif"
ss_tif = filename + "ss.tif"
src_tif = filename + "src.tif"
Outletmv = filename + "_Outletmv.shp"
ss21_tif = filename + "ss21.tif"
ssa21_tif = filename + "ssa21.tif"
drp21_txt = filename + "drp21.txt"
src21_tif = filename + "src21.tif"
ord22_tif = filename + "ord22.tif"
tree22_txt = filename + "tree22.txt"
coord22_txt = filename + "coord22.txt"
net22_shp = filename + "net22.shp"
w22_tif = filename + "w22.tif"

subwatersheds_shp = filename + "subwater.shp"
select_sub = filename + "subwater_select.shp"
out_sub = filename + "subwater_final.shp"

#check if output shapefiles exist - if yes, an error in TauDEM tools will occur unless path is changed.
outlist = [subwatersheds_shp, out_sub, net22_shp, net19_shp]

print "files ", os.listdir(path)

for file in outlist:
    try:
        if file in os.listdir(path):
            print file, " already exists in folder. Change name or path."
            quit()
    except NameError:
        pass

print "Delineating watershed"

# Process: Pit Remove 3-8
arcpy.PitRemove_TDEM(inDEM, "", "", "8", fel_tif)

# Process: D8 Flow Directions 9
arcpy.D8FlowDir_TDEM(fel_tif, "8", p_tif, sd8_tif)

# Process: Grid Network 11
arcpy.GridNetwork_TDEM(p_tif, "8", "", "", "", gord_tif, plen_tif, tlen_tif)

# Process: D-Infinity Flow Directions 12
arcpy.DinfFlowDir_TDEM(fel_tif, "8", ang_tif, slp_tif)

# Process: D-Infinity Contributing Area 13
arcpy.AreaDinf_TDEM(ang_tif, "", "", "true", "8", sca_tif)

# Process: D8 Contributing Area 10
arcpy.D8ContributingArea_TDEM(p_tif, "", "", "true", "8", ad8_tif)

# Process: Stream Definition By Threshold 14
arcpy.StreamDefByThreshold_TDEM(ad8_tif, "", "100", "8", src_tif)

if os.path.isfile(Gauge_shp) == True:
    # Process: Move Outlets To Streams 16
    arcpy.MoveOutletsToStreams_TDEM(p_tif, src_tif, Gauge_shp, "50", "8", Outletmv)
else:
    Outletmv = ""



# Process: D8 Contributing Area 17
arcpy.D8ContributingArea_TDEM(p_tif, Outletmv, "", "true", "8", ssa_tif)

# Process: Stream Definition By Threshold 18
arcpy.StreamDefByThreshold_TDEM(ssa_tif, "", "100", "8", src18_tif)

# Process: Stream Reach And Watershed 19
arcpy.StreamReachAndWatershed_TDEM(fel_tif, p_tif, ad8_tif, src18_tif, Outletmv, "false", "8", ord19_tif, tree19_txt, coord19_txt, net19_shp, w19_tif)

# Process: Peuker Douglas 20
arcpy.PeukerDouglas_TDEM(fel_tif, "0.4", "0.1", "0.05", "8", ss_tif)

# Process: Peuker Douglas Stream Definition 21. 6th input is #cells tributary needed to form stream.
arcpy.PeukerDouglasStreamDef_TDEM(fel_tif, p_tif, "0.4", "0.1", "0.05", "50", "true", Outletmv, "", ad8_tif, "8", ss21_tif, ssa21_tif, src21_tif, drp21_txt, "true", "5", "500", "10", "true")

# Process: Stream Reach And Watershed 22
arcpy.StreamReachAndWatershed_TDEM(fel_tif, p_tif, ad8_tif, src21_tif, Outletmv, "false", "8", ord22_tif, tree22_txt, coord22_txt, net22_shp, w22_tif)



#post processing
#TauDEM toolbox has a builtin raster --> shapefile converter, but it just calls raster --> polygon and doesn't merge tiny pieces.

# Process: Raster to Polygon
arcpy.RasterToPolygon_conversion(w22_tif, subwatersheds_shp, "SIMPLIFY", "Value")  #convert raster to polygon


# Process: Add Geometry Attributes
arcpy.AddGeometryAttributes_management(subwatersheds_shp, "AREA", "", "ACRES", "")

#make temp layer for editing
arcpy.MakeFeatureLayer_management(subwatersheds_shp, select_sub)

#merge polygons with area < 1 acre with the adjacent polygon with longest shared side length. May want to change area threshold
arcpy.SelectLayerByAttribute_management(select_sub, "NEW_SELECTION", '"POLY_AREA" < 1.0')

# "LENGTH" = merge with adjacent of longest sidelength
arcpy.Eliminate_management(select_sub, out_sub, "LENGTH", "", "")

print "done"
